package:
  name: md-dev
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
source:
  path: ../..

build:
  preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - md


about:
  home: https://github.com/mannimaster/compsci-proj-md
  license: GNU Public License v3+
  summary: "Simulation of molecular dynamics applied to ionic solids"
