package:
  name: md
  version: {{ GIT_DESCRIBE_TAG+ '+' +GIT_BUILD_STR }}
source:
  path: ../..

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - md


about:
  home: https://github.com/mannimaster/compsci-proj-md
  license: GNU Public License v3+
  summary: "Simulation of molecular dynamics applied to ionic solids"
